### ISSUE TITLE
1.3.5 Version not filling

### ISSUE THREAD

**Issue by Dellybro** [bartgryszko/react-native-circular-progress#229] opened 2020-01-21 23:39 UTC
When i give the component a fill, it does not render the fill nor does it render new fills.

This seemed to work in 1.3.4, all of a sudden my program has stopped working the way it was supposed to

**Comment by JacopoKenzo** [comment] 2020-01-22 02:03
Same problem here! 😓

**Comment by Dellybro** [comment] 2020-01-22 18:24
For now i think everyone who is having this issue, should just install version 1.3.4 that is what i've done and the component should go back to working.

**Comment by aboveyunhai** [comment] 2020-01-23 20:59
Please read the #227 regarding the issue merge.
Duplicate of #228 ,  check the fix.

**Closed** 2021-02-07 08:00 UTC
