### ISSUE TITLE
Progress tends to lag

### ISSUE THREAD

**Issue by RukaiJohn** [bartgryszko/react-native-circular-progress#165] opened 2018-12-27 07:39 UTC
I'm not sure what I'm doing wrong, but while the progress is active, it tends to lag while it's progressing. For example, it would stop noticeably in some spots and continue. I'm trying to do 3 and 10 seconds.

what i did:

       <AnimatedCircularProgress
                ref={ref => (this.circularProgress = ref)}
                size={200}
                width={20}
                fill={3}
                tintColor="#00e0ff"
                backgroundColor="#3d5875"
              >
                   {fill => (
                      <Text
                        style={{
                         fontSize: 150,
                        color: "red",
                   
                    }}
                       >
                       {this.state.timer}
                     </Text>
                )}
              </AnimatedCircularProgress>

then I called it from a method: 

this.circularProgress.animate(100, 3000, Easing.ease);
this.circularProgress.animate(100, 10000, Easing.ease);

**Comment by markusl** [comment] 2018-12-29 17:31
Duplicate of #150

**Closed by markusl** 2018-12-29 17:31 UTC
